### ISSUE TITLE
Notice on custom post type edit index

### ISSUE THREAD

**Issue by bunglegrind** [wp-media/adminimize#165]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

Done

**Describe the bug**
When browsing on `/wp-admin/edit.php?page=tec-events-settings&post_type=tribe_events&update-message-the-events-calendar=1` (events calendar plugin)
the following error appears:
`Notice: Undefined index: post_type in [...]/wp-content/plugins/adminimize/adminimize.php on line 918`

I suspect it's a regression introduced in 1.11.11.

**Comment by bueltge** [comment]
Thanks @bunglegrind, should be fixed with the last commit ^

**Comment by bunglegrind** [comment]
you're welcome!
